version: "3.3"
services:
  crypto-web:
    container_name: crypto-webserver
    image: crypto-backend
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - PORT=5000
      - METAMASK_ADDRESS="<replace here>"
    ports:
      - "5000:5000"
    volumes:
      - /usr/src/app/node_modules
    depends_on:
      - crypto-database
      - crypto-blockchain
    networks:
      - crypto
  crypto-blockchain:
    container_name: crypto-blockchain
    image: "ethereum/client-go:latest"
    # So many bad security practices in the next line, but fixing all of those for a production environment could be an entire seminar topic on its own.
    entrypoint: geth --http --http.addr 0.0.0.0 --http.corsdomain "*" --http.vhosts '*' --http.api web3,eth,debug,personal,net --ws --ws.addr 0.0.0.0 --ws.port 8546 --ws.api eth,net,web3 --ws.origins '*' --datadir /home/geth/ --allow-insecure-unlock --dev
    ports:
      - "8545:8545"
      - "8546:8546"
    expose:
      - 8545
      - 8546
    volumes:
      - /home/geth
    networks:
      - crypto
  crypto-database:
    container_name: crypto-database
    image: "mongo:5.0"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=RubyRose
      - MONGO_INITDB_ROOT_PASSWORD=thanatoast
    # Open for development purposes. Comment out in a release build, as it only needs to be available internally
    ports:
      - "27017:27017"
    expose:
      - 27017
    networks:
      - crypto
networks:
  crypto:
    driver: bridge