version: "3.3"
services:
  # crypto-web:
  #   container_name: crypto-webserver
  #   image: crypto-backend
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile
  #   environment:
  #     - PORT=5000
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  crypto-blockchain:
    container_name: crypto-blockchain
    image: "ethereum/client-go:stable"
    entrypoint: geth --http --http.addr 0.0.0.0 --http.corsdomain "*" --http.api web3,eth,debug,personal,net --datadir /home/geth/ --dev --allow-insecure-unlock
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
  crypto-database:
    container_name: crypto-database
    image: "mongo:5.0"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=RubyRose
      - MONGO_INITDB_ROOT_PASSWORD=thanatoast
    ports:
      - "27017:27017"
  # crypto-initializer:
  #   container_name: crypto-initializer
  #   image: crypto-backend
  #   entrypoint: npm run setup
  #   depends_on:
  #     - "crypto-blockchain"
  #     - "crypto-database"