version: "3.3"
services:
  # crypto-web:
  #   container_name: crypto-webserver
  #   image: crypto-backend
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile
  #   environment:
  #     - PORT=5000
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   depends_on:
  #     - crypto-database
  #     - crypto-blockchain
  crypto-blockchain:
    container_name: crypto-blockchain
    image: "ethereum/client-go:latest"
    entrypoint: geth --http --http.addr 0.0.0.0 --http.corsdomain "*" --http.api web3,eth,debug,personal,net --ws --ws.addr 0.0.0.0 --ws.port 8546 --ws.api eth,net,web3 --ws.origins '*' --datadir /home/geth/ --allow-insecure-unlock --dev --miner.threads=4
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
    volumes:
      - /home/geth
  crypto-database:
    container_name: crypto-database
    image: "mongo:5.0"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=RubyRose
      - MONGO_INITDB_ROOT_PASSWORD=thanatoast
    ports:
      - "27017:27017"
  # crypto-initializer:
  #   container_name: crypto-initializer
  #   image: crypto-backend
  #   entrypoint: npm run setup
  #   depends_on:
  #     - "crypto-blockchain"
  #     - "crypto-database"